### ISSUE TITLE
script to generate the centos oval files.

### ISSUE THREAD

**Issue by stafwag** [Sep0lkit/oval-for-el#1]
Hi,

Nice project! But I couldn't find the script to generate the oval files for Centos.

Are you willing to release it?

Kind regards,
--
staf

**Comment by Capashenn** [comment]
Yes, it would be great if you could share the script to generate the oval files for Centos.
Excellent idea btw !

**Comment by Sep0lkit** [comment]
There is just a python script which convert the redhat oval to adapt for centos and add oval for centos,  so i make this cloud task and sync to github.

if someone need, i will push the convert script here later.

**Comment by stafwag** [comment]
Hi,

It'd be nice to have the script available. 
It's your  choice to release it or not of course.

kind regards,

--
staf

**Comment by Sep0lkit** [comment]
> Hi,
> 
> It'd be nice to have the script available.
> It's your choice to release it or not of course.
> 
> kind regards,
> 
> --
> staf

update here: https://github.com/Sep0lkit/oval-for-el/tree/master/scripts
the document also updated to readme.

**Comment by nunofernandes** [comment]
Tried to run that script but it doesn't seem to work:

```
$ wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2
$ bunzip2 com.redhat.rhsa-all.xml.bz2 
$ ./rh2el.py com.redhat.rhsa-all.xml com.redhat.centos-all.xml 
('red hat sign key: %s not found .\n', 'oval:com.redhat.rhba:ste:20150364002')
('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20190966002')
('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20100889010')
('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20100889002')
('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20140741002')
$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
$ oscap oval eval com.redhat.centos-all.xml
Definition oval:com.redhat.rhsa:def:20193981: true
Definition oval:com.redhat.rhsa:def:20193979: true
Definition oval:com.redhat.rhsa:def:20193978: true
Definition oval:com.redhat.rhsa:def:20193976: true
...
Evaluation done.
```

Everything seems to be true (vunerable). Any ideas?

**Comment by Sep0lkit** [comment]
> Tried to run that script but it doesn't seem to work:
> 
> ```
> $ wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2
> $ bunzip2 com.redhat.rhsa-all.xml.bz2 
> $ ./rh2el.py com.redhat.rhsa-all.xml com.redhat.centos-all.xml 
> ('red hat sign key: %s not found .\n', 'oval:com.redhat.rhba:ste:20150364002')
> ('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20190966002')
> ('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20100889010')
> ('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20100889002')
> ('red hat sign key: %s not found .\n', 'oval:com.redhat.rhsa:ste:20140741002')
> $ cat /etc/redhat-release 
> CentOS Linux release 7.7.1908 (Core)
> $ oscap oval eval com.redhat.centos-all.xml
> Definition oval:com.redhat.rhsa:def:20193981: true
> Definition oval:com.redhat.rhsa:def:20193979: true
> Definition oval:com.redhat.rhsa:def:20193978: true
> Definition oval:com.redhat.rhsa:def:20193976: true
> ...
> Evaluation done.
> ```
> 
> Everything seems to be true (vunerable). Any ideas?

Thanks for your report.
It seems redhat redefine there oval structures on November, you can try:
git reset --hard d16962d3b1dd218fb688ad14cf8a29aff4826dcd
oscap oval eval com.redhat.rhsa-EL7-Critical.xml

it works well.

so i looked at the oval file,  it changed the oval criteria. example: oval:com.redhat.rhba:def:20150364
beforce:
![image](https://user-images.githubusercontent.com/1725575/69895591-e4d8d500-136d-11ea-91b1-694799e43b02.png)
after:
![image](https://user-images.githubusercontent.com/1725575/69895594-fcb05900-136d-11ea-9fd8-1342f4c33e68.png)

I think it is wrong with oval grammar, i will try redhat oval on redhat linux.

**Comment by nunofernandes** [comment]
I did tried redhat oval on redhat linux and it seemed to work:

```
$ docker run -ti --rm --entrypoint=bash registry.access.redhat.com/rhel7/openscap -c 'wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2 -q -O - | bzcat - > com.redhat.rhsa-all.xml; oscap oval eval com.redhat.rhsa-all.xml'
Definition oval:com.redhat.rhsa:def:20193981: false
Definition oval:com.redhat.rhsa:def:20193979: false
Definition oval:com.redhat.rhsa:def:20193978: false
Definition oval:com.redhat.rhsa:def:20193976: false
Definition oval:com.redhat.rhsa:def:20193968: false
Definition oval:com.redhat.rhsa:def:20193950: false
Definition oval:com.redhat.rhsa:def:20193888: false
Definition oval:com.redhat.rhsa:def:20193887: false
Definition oval:com.redhat.rhsa:def:20193878: false
....
Definition oval:com.redhat.rhba:def:20070304: false
Definition oval:com.redhat.rhba:def:20070026: false
Evaluation done.
```

**Comment by Sep0lkit** [comment]
> n -ti --rm --entrypoint=bash registry.access.redhat.com/rhel7/openscap -c 'wget https://www.redhat.com/securi

Yeah, I tested on redhat, it works well.

Redhat add all defines with a tests like:
id="oval:com.redhat.rhsa:tst:20193391006" version="634" comment="Red Hat Enterprise Linux must be installed" check="none satisfy"

Judgment logic has changed significantly, so i need to change the program.

now, changed is finished and it works well on centos, but i need to test and it works well,  i will update here.

PS: after the redhat oval changed, it is much better for adapted to centos.

**Comment by Sep0lkit** [comment]
> I did tried redhat oval on redhat linux and it seemed to work:
> 
> ```
> $ docker run -ti --rm --entrypoint=bash registry.access.redhat.com/rhel7/openscap -c 'wget https://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml.bz2 -q -O - | bzcat - > com.redhat.rhsa-all.xml; oscap oval eval com.redhat.rhsa-all.xml'
> Definition oval:com.redhat.rhsa:def:20193981: false
> Definition oval:com.redhat.rhsa:def:20193979: false
> Definition oval:com.redhat.rhsa:def:20193978: false
> Definition oval:com.redhat.rhsa:def:20193976: false
> Definition oval:com.redhat.rhsa:def:20193968: false
> Definition oval:com.redhat.rhsa:def:20193950: false
> Definition oval:com.redhat.rhsa:def:20193888: false
> Definition oval:com.redhat.rhsa:def:20193887: false
> Definition oval:com.redhat.rhsa:def:20193878: false
> ....
> Definition oval:com.redhat.rhba:def:20070304: false
> Definition oval:com.redhat.rhba:def:20070026: false
> Evaluation done.
> ```
updated the scripts and oval files, please try

**Comment by nunofernandes** [comment]
Hello,

Yeap :fireworks: it works!

Thanks,
Nuno Fernandes
